version: '3.8'

services:
  fastapi-service:
    # Replace 'your_dockerhub_username' with your actual username
    image: elvispro1993/fleetdash-backend:latest
    container_name: fleetdash_app
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - fleet_net

  postgres:
    image: postgres:15-alpine
    container_name: fleetdash_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - fleet_net

volumes:
  postgres_prod_data:

networks:
  fleet_net:
    driver: bridge