version: '3.8'

services:
  fastapi-service:
    # Your Docker Hub image
    image: elvispro1993/fleetdash-backend:latest
    container_name: fleetdash_app
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    # CRITICAL: This must match the service name below
    depends_on:
      - fastapi-db
    networks:
      - fleet_net

  # Renamed service from 'postgres' to 'fastapi-db' as requested
  fastapi-db:
    image: postgres:15-alpine
    container_name: fleetdash_db
    restart: always
    # These variables create the database inside the container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - fleet_net

volumes:
  postgres_prod_data:

networks:
  fleet_net:
    driver: bridge