name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # FORCE NO CACHE: This ensures every line of code is re-read
          no-cache: true 
          tags: elvispro1993/fleetdash-backend:latest

      - name: Copy Compose File to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GCP_IP }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.prod.yml"
          target: "~/fleetdash/"

      - name: Deploy on GCP
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_IP }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to directory
            cd ~/fleetdash
            
            # 1. Pull the newly pushed image (without using local server cache)
            docker compose -f docker-compose.prod.yml pull
            
            # 2. Restart services and FORCE RECREATION 
            # This ignores existing containers and starts them fresh
            docker compose -f docker-compose.prod.yml up -d --remove-orphans --force-recreate
            
            # 3. Wait for the database to be ready
            echo "Waiting for database..."
            sleep 15
            
            # 4. Run Migrations
            echo "Running migrations..."
            docker compose -f docker-compose.prod.yml exec -T fastapi-service alembic upgrade head
            
            # 5. NUCLEAR CLEANUP: Remove all old images and build cache on the server
            # This prevents your 8.7GB disk from filling up
            docker system prune -af